package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTabInfoTagRelated;
import org.linlinjava.litemall.db.domain.LitemallTabInfoTagRelatedExample;

public interface LitemallTabInfoTagRelatedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    long countByExample(LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int insert(LitemallTabInfoTagRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTabInfoTagRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTagRelated selectOneByExample(LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTagRelated selectOneByExampleSelective(@Param("example") LitemallTabInfoTagRelatedExample example, @Param("selective") LitemallTabInfoTagRelated.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallTabInfoTagRelated> selectByExampleSelective(@Param("example") LitemallTabInfoTagRelatedExample example, @Param("selective") LitemallTabInfoTagRelated.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    List<LitemallTabInfoTagRelated> selectByExample(LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTagRelated selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTabInfoTagRelated.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    LitemallTabInfoTagRelated selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTagRelated selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTabInfoTagRelated record, @Param("example") LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTabInfoTagRelated record, @Param("example") LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTabInfoTagRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTabInfoTagRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallTabInfoTagRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag_related
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}