package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTabInfoTag;
import org.linlinjava.litemall.db.domain.LitemallTabInfoTagExample;

import java.util.List;

public interface LitemallTabInfoTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    long countByExample(LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int insert(LitemallTabInfoTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTabInfoTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTag selectOneByExample(LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTag selectOneByExampleSelective(@Param("example") LitemallTabInfoTagExample example, @Param("selective") LitemallTabInfoTag.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallTabInfoTag> selectByExampleSelective(@Param("example") LitemallTabInfoTagExample example, @Param("selective") LitemallTabInfoTag.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    List<LitemallTabInfoTag> selectByExample(LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTag selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTabInfoTag.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    LitemallTabInfoTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoTag selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTabInfoTag record, @Param("example") LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTabInfoTag record, @Param("example") LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTabInfoTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTabInfoTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallTabInfoTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_tag
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * 查询当前资讯 的标签列表
     * */
    List<LitemallTabInfoTag>selectInfoTag (Integer info_id);
//     LitemallTabInfoTag selectInfoTag(Integer info_id);
    /**
     * 查询所有标签（限制6个）
     * */
    List<LitemallTabInfoTag> selectAllTag(LitemallTabInfoTagExample example);

    LitemallTabInfoTag selectTagName(Integer info_id);
}