package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallFriendshipLink;
import org.linlinjava.litemall.db.domain.LitemallFriendshipLinkExample;

public interface LitemallFriendshipLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    long countByExample(LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int insert(LitemallFriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int insertSelective(LitemallFriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFriendshipLink selectOneByExample(LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFriendshipLink selectOneByExampleSelective(@Param("example") LitemallFriendshipLinkExample example, @Param("selective") LitemallFriendshipLink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallFriendshipLink> selectByExampleSelective(@Param("example") LitemallFriendshipLinkExample example, @Param("selective") LitemallFriendshipLink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    List<LitemallFriendshipLink> selectByExample(LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFriendshipLink selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallFriendshipLink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    LitemallFriendshipLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFriendshipLink selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallFriendshipLink record, @Param("example") LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallFriendshipLink record, @Param("example") LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallFriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallFriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallFriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_friendship_link
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}