package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallBankcardAuthCall;
import org.linlinjava.litemall.db.domain.LitemallBankcardAuthCallExample;
import org.linlinjava.litemall.db.domain.LitemallBankcardAuthCallWithBLOBs;

public interface LitemallBankcardAuthCallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    long countByExample(LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int insert(LitemallBankcardAuthCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int insertSelective(LitemallBankcardAuthCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBankcardAuthCall selectOneByExample(LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBankcardAuthCallWithBLOBs selectOneByExampleSelective(@Param("example") LitemallBankcardAuthCallExample example, @Param("selective") LitemallBankcardAuthCallWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBankcardAuthCallWithBLOBs selectOneByExampleWithBLOBs(LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallBankcardAuthCallWithBLOBs> selectByExampleSelective(@Param("example") LitemallBankcardAuthCallExample example, @Param("selective") LitemallBankcardAuthCallWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    List<LitemallBankcardAuthCallWithBLOBs> selectByExampleWithBLOBs(LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    List<LitemallBankcardAuthCall> selectByExample(LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBankcardAuthCallWithBLOBs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallBankcardAuthCallWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    LitemallBankcardAuthCallWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallBankcardAuthCallWithBLOBs selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallBankcardAuthCallWithBLOBs record, @Param("example") LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallBankcardAuthCallWithBLOBs record, @Param("example") LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallBankcardAuthCall record, @Param("example") LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallBankcardAuthCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallBankcardAuthCallWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallBankcardAuthCall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallBankcardAuthCallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard_auth_call
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}