package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMoneyApply;
import org.linlinjava.litemall.db.domain.LitemallMoneyApplyExample;

public interface LitemallMoneyApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    long countByExample(LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int insert(LitemallMoneyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMoneyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMoneyApply selectOneByExample(LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMoneyApply selectOneByExampleSelective(@Param("example") LitemallMoneyApplyExample example, @Param("selective") LitemallMoneyApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallMoneyApply> selectByExampleSelective(@Param("example") LitemallMoneyApplyExample example, @Param("selective") LitemallMoneyApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    List<LitemallMoneyApply> selectByExample(LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMoneyApply selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMoneyApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    LitemallMoneyApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallMoneyApply selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMoneyApply record, @Param("example") LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMoneyApply record, @Param("example") LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMoneyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMoneyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallMoneyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_money_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}