package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTabInfoClass;
import org.linlinjava.litemall.db.domain.LitemallTabInfoClassExample;

import java.util.List;

public interface LitemallTabInfoClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    long countByExample(LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int insert(LitemallTabInfoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTabInfoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoClass selectOneByExample(LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoClass selectOneByExampleSelective(@Param("example") LitemallTabInfoClassExample example, @Param("selective") LitemallTabInfoClass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallTabInfoClass> selectByExampleSelective(@Param("example") LitemallTabInfoClassExample example, @Param("selective") LitemallTabInfoClass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    List<LitemallTabInfoClass> selectByExample(LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoClass selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTabInfoClass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    LitemallTabInfoClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoClass selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTabInfoClass record, @Param("example") LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTabInfoClass record, @Param("example") LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTabInfoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTabInfoClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallTabInfoClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}