package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallExpressOrderCargo;
import org.linlinjava.litemall.db.domain.LitemallExpressOrderCargoExample;

public interface LitemallExpressOrderCargoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    long countByExample(LitemallExpressOrderCargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallExpressOrderCargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    int insert(LitemallExpressOrderCargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    int insertSelective(LitemallExpressOrderCargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExpressOrderCargo selectOneByExample(LitemallExpressOrderCargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallExpressOrderCargo selectOneByExampleSelective(@Param("example") LitemallExpressOrderCargoExample example, @Param("selective") LitemallExpressOrderCargo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallExpressOrderCargo> selectByExampleSelective(@Param("example") LitemallExpressOrderCargoExample example, @Param("selective") LitemallExpressOrderCargo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    List<LitemallExpressOrderCargo> selectByExample(LitemallExpressOrderCargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallExpressOrderCargo record, @Param("example") LitemallExpressOrderCargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallExpressOrderCargo record, @Param("example") LitemallExpressOrderCargoExample example);
}