package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTabInfoContent;
import org.linlinjava.litemall.db.domain.LitemallTabInfoContentExample;

import java.util.List;

public interface LitemallTabInfoContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    long countByExample(LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int insert(LitemallTabInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTabInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoContent selectOneByExample(LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoContent selectOneByExampleSelective(@Param("example") LitemallTabInfoContentExample example, @Param("selective") LitemallTabInfoContent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoContent selectOneByExampleWithBLOBs(LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallTabInfoContent> selectByExampleSelective(@Param("example") LitemallTabInfoContentExample example, @Param("selective") LitemallTabInfoContent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    List<LitemallTabInfoContent> selectByExampleWithBLOBs(LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    List<LitemallTabInfoContent> selectByExample(LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoContent selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTabInfoContent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    LitemallTabInfoContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallTabInfoContent selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTabInfoContent record, @Param("example") LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallTabInfoContent record, @Param("example") LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTabInfoContent record, @Param("example") LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTabInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallTabInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTabInfoContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallTabInfoContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_tab_info_content
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);

    LitemallTabInfoContent selectInfoContent(Integer info_id);
}