package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallNews;
import org.linlinjava.litemall.db.domain.LitemallNewsExample;

public interface LitemallNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    long countByExample(LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int insert(LitemallNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int insertSelective(LitemallNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallNews selectOneByExample(LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallNews selectOneByExampleSelective(@Param("example") LitemallNewsExample example, @Param("selective") LitemallNews.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallNews selectOneByExampleWithBLOBs(LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallNews> selectByExampleSelective(@Param("example") LitemallNewsExample example, @Param("selective") LitemallNews.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    List<LitemallNews> selectByExampleWithBLOBs(LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    List<LitemallNews> selectByExample(LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallNews selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallNews.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    LitemallNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallNews selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallNews record, @Param("example") LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallNews record, @Param("example") LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallNews record, @Param("example") LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_news
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);


}