package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCommission;
import org.linlinjava.litemall.db.domain.LitemallCommissionExample;

public interface LitemallCommissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    long countByExample(LitemallCommissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCommissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int insert(LitemallCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCommission selectOneByExample(LitemallCommissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCommission selectOneByExampleSelective(@Param("example") LitemallCommissionExample example, @Param("selective") LitemallCommission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallCommission> selectByExampleSelective(@Param("example") LitemallCommissionExample example, @Param("selective") LitemallCommission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    List<LitemallCommission> selectByExample(LitemallCommissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCommission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCommission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    LitemallCommission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCommission record, @Param("example") LitemallCommissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCommission record, @Param("example") LitemallCommissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_commission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCommission record);
}