package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class LitemallCodeTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.code_type
     *
     * @mbg.generated
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.code_name
     *
     * @mbg.generated
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.code_unit
     *
     * @mbg.generated
     */
    private String codeUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.valid_flag
     *
     * @mbg.generated
     */
    private String validFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_code_tree.dis_order
     *
     * @mbg.generated
     */
    private Integer disOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.id
     *
     * @return the value of litemall_code_tree.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.id
     *
     * @param id the value for litemall_code_tree.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.pid
     *
     * @return the value of litemall_code_tree.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.pid
     *
     * @param pid the value for litemall_code_tree.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.code_type
     *
     * @return the value of litemall_code_tree.code_type
     *
     * @mbg.generated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.code_type
     *
     * @param codeType the value for litemall_code_tree.code_type
     *
     * @mbg.generated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.code_name
     *
     * @return the value of litemall_code_tree.code_name
     *
     * @mbg.generated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.code_name
     *
     * @param codeName the value for litemall_code_tree.code_name
     *
     * @mbg.generated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.code_unit
     *
     * @return the value of litemall_code_tree.code_unit
     *
     * @mbg.generated
     */
    public String getCodeUnit() {
        return codeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.code_unit
     *
     * @param codeUnit the value for litemall_code_tree.code_unit
     *
     * @mbg.generated
     */
    public void setCodeUnit(String codeUnit) {
        this.codeUnit = codeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.valid_flag
     *
     * @return the value of litemall_code_tree.valid_flag
     *
     * @mbg.generated
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.valid_flag
     *
     * @param validFlag the value for litemall_code_tree.valid_flag
     *
     * @mbg.generated
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_code_tree.dis_order
     *
     * @return the value of litemall_code_tree.dis_order
     *
     * @mbg.generated
     */
    public Integer getDisOrder() {
        return disOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_code_tree.dis_order
     *
     * @param disOrder the value for litemall_code_tree.dis_order
     *
     * @mbg.generated
     */
    public void setDisOrder(Integer disOrder) {
        this.disOrder = disOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_code_tree
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", codeType=").append(codeType);
        sb.append(", codeName=").append(codeName);
        sb.append(", codeUnit=").append(codeUnit);
        sb.append(", validFlag=").append(validFlag);
        sb.append(", disOrder=").append(disOrder);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_code_tree
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallCodeTree other = (LitemallCodeTree) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getCodeType() == null ? other.getCodeType() == null : this.getCodeType().equals(other.getCodeType()))
            && (this.getCodeName() == null ? other.getCodeName() == null : this.getCodeName().equals(other.getCodeName()))
            && (this.getCodeUnit() == null ? other.getCodeUnit() == null : this.getCodeUnit().equals(other.getCodeUnit()))
            && (this.getValidFlag() == null ? other.getValidFlag() == null : this.getValidFlag().equals(other.getValidFlag()))
            && (this.getDisOrder() == null ? other.getDisOrder() == null : this.getDisOrder().equals(other.getDisOrder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_code_tree
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getCodeType() == null) ? 0 : getCodeType().hashCode());
        result = prime * result + ((getCodeName() == null) ? 0 : getCodeName().hashCode());
        result = prime * result + ((getCodeUnit() == null) ? 0 : getCodeUnit().hashCode());
        result = prime * result + ((getValidFlag() == null) ? 0 : getValidFlag().hashCode());
        result = prime * result + ((getDisOrder() == null) ? 0 : getDisOrder().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_code_tree
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        pid("pid", "pid", "INTEGER", false),
        codeType("code_type", "codeType", "VARCHAR", false),
        codeName("code_name", "codeName", "VARCHAR", false),
        codeUnit("code_unit", "codeUnit", "VARCHAR", false),
        validFlag("valid_flag", "validFlag", "VARCHAR", false),
        disOrder("dis_order", "disOrder", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_code_tree
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}