package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallBankcard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.bank_id
     *
     * @mbg.generated
     */
    private Integer bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.bank_city
     *
     * @mbg.generated
     */
    private String bankCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.bank_code
     *
     * @mbg.generated
     */
    private String bankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.bank_county
     *
     * @mbg.generated
     */
    private String bankCounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.bank_province
     *
     * @mbg.generated
     */
    private String bankProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.bankname
     *
     * @mbg.generated
     */
    private String bankname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.expiry_date
     *
     * @mbg.generated
     */
    private LocalDateTime expiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.preferred
     *
     * @mbg.generated
     */
    private Boolean preferred;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.subbranch
     *
     * @mbg.generated
     */
    private String subbranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_bankcard.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.id
     *
     * @return the value of litemall_bankcard.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.id
     *
     * @param id the value for litemall_bankcard.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.user_id
     *
     * @return the value of litemall_bankcard.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.user_id
     *
     * @param userId the value for litemall_bankcard.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.user_name
     *
     * @return the value of litemall_bankcard.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.user_name
     *
     * @param userName the value for litemall_bankcard.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.bank_id
     *
     * @return the value of litemall_bankcard.bank_id
     *
     * @mbg.generated
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.bank_id
     *
     * @param bankId the value for litemall_bankcard.bank_id
     *
     * @mbg.generated
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.bank_city
     *
     * @return the value of litemall_bankcard.bank_city
     *
     * @mbg.generated
     */
    public String getBankCity() {
        return bankCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.bank_city
     *
     * @param bankCity the value for litemall_bankcard.bank_city
     *
     * @mbg.generated
     */
    public void setBankCity(String bankCity) {
        this.bankCity = bankCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.bank_code
     *
     * @return the value of litemall_bankcard.bank_code
     *
     * @mbg.generated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.bank_code
     *
     * @param bankCode the value for litemall_bankcard.bank_code
     *
     * @mbg.generated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.bank_county
     *
     * @return the value of litemall_bankcard.bank_county
     *
     * @mbg.generated
     */
    public String getBankCounty() {
        return bankCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.bank_county
     *
     * @param bankCounty the value for litemall_bankcard.bank_county
     *
     * @mbg.generated
     */
    public void setBankCounty(String bankCounty) {
        this.bankCounty = bankCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.bank_province
     *
     * @return the value of litemall_bankcard.bank_province
     *
     * @mbg.generated
     */
    public String getBankProvince() {
        return bankProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.bank_province
     *
     * @param bankProvince the value for litemall_bankcard.bank_province
     *
     * @mbg.generated
     */
    public void setBankProvince(String bankProvince) {
        this.bankProvince = bankProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.bankname
     *
     * @return the value of litemall_bankcard.bankname
     *
     * @mbg.generated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.bankname
     *
     * @param bankname the value for litemall_bankcard.bankname
     *
     * @mbg.generated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.type
     *
     * @return the value of litemall_bankcard.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.type
     *
     * @param type the value for litemall_bankcard.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.expiry_date
     *
     * @return the value of litemall_bankcard.expiry_date
     *
     * @mbg.generated
     */
    public LocalDateTime getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.expiry_date
     *
     * @param expiryDate the value for litemall_bankcard.expiry_date
     *
     * @mbg.generated
     */
    public void setExpiryDate(LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.memo
     *
     * @return the value of litemall_bankcard.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.memo
     *
     * @param memo the value for litemall_bankcard.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.mobile
     *
     * @return the value of litemall_bankcard.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.mobile
     *
     * @param mobile the value for litemall_bankcard.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.number
     *
     * @return the value of litemall_bankcard.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.number
     *
     * @param number the value for litemall_bankcard.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.preferred
     *
     * @return the value of litemall_bankcard.preferred
     *
     * @mbg.generated
     */
    public Boolean getPreferred() {
        return preferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.preferred
     *
     * @param preferred the value for litemall_bankcard.preferred
     *
     * @mbg.generated
     */
    public void setPreferred(Boolean preferred) {
        this.preferred = preferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.subbranch
     *
     * @return the value of litemall_bankcard.subbranch
     *
     * @mbg.generated
     */
    public String getSubbranch() {
        return subbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.subbranch
     *
     * @param subbranch the value for litemall_bankcard.subbranch
     *
     * @mbg.generated
     */
    public void setSubbranch(String subbranch) {
        this.subbranch = subbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.add_time
     *
     * @return the value of litemall_bankcard.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.add_time
     *
     * @param addTime the value for litemall_bankcard.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.update_time
     *
     * @return the value of litemall_bankcard.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.update_time
     *
     * @param updateTime the value for litemall_bankcard.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_bankcard.deleted
     *
     * @return the value of litemall_bankcard.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_bankcard.deleted
     *
     * @param deleted the value for litemall_bankcard.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", bankId=").append(bankId);
        sb.append(", bankCity=").append(bankCity);
        sb.append(", bankCode=").append(bankCode);
        sb.append(", bankCounty=").append(bankCounty);
        sb.append(", bankProvince=").append(bankProvince);
        sb.append(", bankname=").append(bankname);
        sb.append(", type=").append(type);
        sb.append(", expiryDate=").append(expiryDate);
        sb.append(", memo=").append(memo);
        sb.append(", mobile=").append(mobile);
        sb.append(", number=").append(number);
        sb.append(", preferred=").append(preferred);
        sb.append(", subbranch=").append(subbranch);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallBankcard other = (LitemallBankcard) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getBankId() == null ? other.getBankId() == null : this.getBankId().equals(other.getBankId()))
            && (this.getBankCity() == null ? other.getBankCity() == null : this.getBankCity().equals(other.getBankCity()))
            && (this.getBankCode() == null ? other.getBankCode() == null : this.getBankCode().equals(other.getBankCode()))
            && (this.getBankCounty() == null ? other.getBankCounty() == null : this.getBankCounty().equals(other.getBankCounty()))
            && (this.getBankProvince() == null ? other.getBankProvince() == null : this.getBankProvince().equals(other.getBankProvince()))
            && (this.getBankname() == null ? other.getBankname() == null : this.getBankname().equals(other.getBankname()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getExpiryDate() == null ? other.getExpiryDate() == null : this.getExpiryDate().equals(other.getExpiryDate()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getPreferred() == null ? other.getPreferred() == null : this.getPreferred().equals(other.getPreferred()))
            && (this.getSubbranch() == null ? other.getSubbranch() == null : this.getSubbranch().equals(other.getSubbranch()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getBankId() == null) ? 0 : getBankId().hashCode());
        result = prime * result + ((getBankCity() == null) ? 0 : getBankCity().hashCode());
        result = prime * result + ((getBankCode() == null) ? 0 : getBankCode().hashCode());
        result = prime * result + ((getBankCounty() == null) ? 0 : getBankCounty().hashCode());
        result = prime * result + ((getBankProvince() == null) ? 0 : getBankProvince().hashCode());
        result = prime * result + ((getBankname() == null) ? 0 : getBankname().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getExpiryDate() == null) ? 0 : getExpiryDate().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getPreferred() == null) ? 0 : getPreferred().hashCode());
        result = prime * result + ((getSubbranch() == null) ? 0 : getSubbranch().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_bankcard
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        userName("user_name", "userName", "VARCHAR", false),
        bankId("bank_id", "bankId", "INTEGER", false),
        bankCity("bank_city", "bankCity", "VARCHAR", false),
        bankCode("bank_code", "bankCode", "VARCHAR", false),
        bankCounty("bank_county", "bankCounty", "VARCHAR", false),
        bankProvince("bank_province", "bankProvince", "VARCHAR", false),
        bankname("bankname", "bankname", "VARCHAR", false),
        type("type", "type", "INTEGER", true),
        expiryDate("expiry_date", "expiryDate", "TIMESTAMP", false),
        memo("memo", "memo", "VARCHAR", false),
        mobile("mobile", "mobile", "VARCHAR", false),
        number("number", "number", "VARCHAR", true),
        preferred("preferred", "preferred", "BIT", false),
        subbranch("subbranch", "subbranch", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_bankcard
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}