package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallExpressOrderCargo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.express_order_id
     *
     * @mbg.generated
     */
    private Integer expressOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.source_area
     *
     * @mbg.generated
     */
    private String sourceArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.product_record_no
     *
     * @mbg.generated
     */
    private String productRecordNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.good_prepard_no
     *
     * @mbg.generated
     */
    private String goodPrepardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.tax_no
     *
     * @mbg.generated
     */
    private String taxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_express_order_cargo.hs_code
     *
     * @mbg.generated
     */
    private String hsCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.id
     *
     * @return the value of litemall_express_order_cargo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.id
     *
     * @param id the value for litemall_express_order_cargo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.express_order_id
     *
     * @return the value of litemall_express_order_cargo.express_order_id
     *
     * @mbg.generated
     */
    public Integer getExpressOrderId() {
        return expressOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.express_order_id
     *
     * @param expressOrderId the value for litemall_express_order_cargo.express_order_id
     *
     * @mbg.generated
     */
    public void setExpressOrderId(Integer expressOrderId) {
        this.expressOrderId = expressOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.name
     *
     * @return the value of litemall_express_order_cargo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.name
     *
     * @param name the value for litemall_express_order_cargo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.count
     *
     * @return the value of litemall_express_order_cargo.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.count
     *
     * @param count the value for litemall_express_order_cargo.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.unit
     *
     * @return the value of litemall_express_order_cargo.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.unit
     *
     * @param unit the value for litemall_express_order_cargo.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.weight
     *
     * @return the value of litemall_express_order_cargo.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.weight
     *
     * @param weight the value for litemall_express_order_cargo.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.amount
     *
     * @return the value of litemall_express_order_cargo.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.amount
     *
     * @param amount the value for litemall_express_order_cargo.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.currency
     *
     * @return the value of litemall_express_order_cargo.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.currency
     *
     * @param currency the value for litemall_express_order_cargo.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.source_area
     *
     * @return the value of litemall_express_order_cargo.source_area
     *
     * @mbg.generated
     */
    public String getSourceArea() {
        return sourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.source_area
     *
     * @param sourceArea the value for litemall_express_order_cargo.source_area
     *
     * @mbg.generated
     */
    public void setSourceArea(String sourceArea) {
        this.sourceArea = sourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.product_record_no
     *
     * @return the value of litemall_express_order_cargo.product_record_no
     *
     * @mbg.generated
     */
    public String getProductRecordNo() {
        return productRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.product_record_no
     *
     * @param productRecordNo the value for litemall_express_order_cargo.product_record_no
     *
     * @mbg.generated
     */
    public void setProductRecordNo(String productRecordNo) {
        this.productRecordNo = productRecordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.good_prepard_no
     *
     * @return the value of litemall_express_order_cargo.good_prepard_no
     *
     * @mbg.generated
     */
    public String getGoodPrepardNo() {
        return goodPrepardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.good_prepard_no
     *
     * @param goodPrepardNo the value for litemall_express_order_cargo.good_prepard_no
     *
     * @mbg.generated
     */
    public void setGoodPrepardNo(String goodPrepardNo) {
        this.goodPrepardNo = goodPrepardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.tax_no
     *
     * @return the value of litemall_express_order_cargo.tax_no
     *
     * @mbg.generated
     */
    public String getTaxNo() {
        return taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.tax_no
     *
     * @param taxNo the value for litemall_express_order_cargo.tax_no
     *
     * @mbg.generated
     */
    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_express_order_cargo.hs_code
     *
     * @return the value of litemall_express_order_cargo.hs_code
     *
     * @mbg.generated
     */
    public String getHsCode() {
        return hsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_express_order_cargo.hs_code
     *
     * @param hsCode the value for litemall_express_order_cargo.hs_code
     *
     * @mbg.generated
     */
    public void setHsCode(String hsCode) {
        this.hsCode = hsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", expressOrderId=").append(expressOrderId);
        sb.append(", name=").append(name);
        sb.append(", count=").append(count);
        sb.append(", unit=").append(unit);
        sb.append(", weight=").append(weight);
        sb.append(", amount=").append(amount);
        sb.append(", currency=").append(currency);
        sb.append(", sourceArea=").append(sourceArea);
        sb.append(", productRecordNo=").append(productRecordNo);
        sb.append(", goodPrepardNo=").append(goodPrepardNo);
        sb.append(", taxNo=").append(taxNo);
        sb.append(", hsCode=").append(hsCode);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallExpressOrderCargo other = (LitemallExpressOrderCargo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getExpressOrderId() == null ? other.getExpressOrderId() == null : this.getExpressOrderId().equals(other.getExpressOrderId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getSourceArea() == null ? other.getSourceArea() == null : this.getSourceArea().equals(other.getSourceArea()))
            && (this.getProductRecordNo() == null ? other.getProductRecordNo() == null : this.getProductRecordNo().equals(other.getProductRecordNo()))
            && (this.getGoodPrepardNo() == null ? other.getGoodPrepardNo() == null : this.getGoodPrepardNo().equals(other.getGoodPrepardNo()))
            && (this.getTaxNo() == null ? other.getTaxNo() == null : this.getTaxNo().equals(other.getTaxNo()))
            && (this.getHsCode() == null ? other.getHsCode() == null : this.getHsCode().equals(other.getHsCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getExpressOrderId() == null) ? 0 : getExpressOrderId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getSourceArea() == null) ? 0 : getSourceArea().hashCode());
        result = prime * result + ((getProductRecordNo() == null) ? 0 : getProductRecordNo().hashCode());
        result = prime * result + ((getGoodPrepardNo() == null) ? 0 : getGoodPrepardNo().hashCode());
        result = prime * result + ((getTaxNo() == null) ? 0 : getTaxNo().hashCode());
        result = prime * result + ((getHsCode() == null) ? 0 : getHsCode().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_express_order_cargo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        expressOrderId("express_order_id", "expressOrderId", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        count("count", "count", "INTEGER", true),
        unit("unit", "unit", "VARCHAR", false),
        weight("weight", "weight", "DECIMAL", false),
        amount("amount", "amount", "DECIMAL", false),
        currency("currency", "currency", "VARCHAR", false),
        sourceArea("source_area", "sourceArea", "VARCHAR", false),
        productRecordNo("product_record_no", "productRecordNo", "VARCHAR", false),
        goodPrepardNo("good_prepard_no", "goodPrepardNo", "VARCHAR", false),
        taxNo("tax_no", "taxNo", "VARCHAR", false),
        hsCode("hs_code", "hsCode", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_express_order_cargo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}